# Library Numpy

In [2]:
import numpy as np

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
a=np.array([['how are you','a',1],[2,3,4 ],['a','b','c' ]])


In [12]:
a

array([['how are you', 'a', '1'],
       ['2', '3', '4'],
       ['a', 'b', 'c']], dtype='<U11')

In [4]:
type(a)

numpy.ndarray

In [13]:
a=np.array([['x','y','z'],[2,3,4 ],['a','b','c']])

In [15]:
a

array([['x', 'y', 'z'],
       ['2', '3', '4'],
       ['a', 'b', 'c']], dtype='<U11')

In [14]:
a.shape

(3, 3)

In [27]:
a=np.array([['x','y','z'],[1,2],['a','b','c']])

In [28]:
a

array([list(['x', 'y', 'z']), list([1, 2]), list(['a', 'b', 'c'])],
      dtype=object)

In [29]:
a.shape

(3,)

In [34]:
b=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]],
           [[1,2,3,4],[4,5,6,7],[7,8,9,10]],
           [[1,2,3,4],[4,5,6,7],[7,8,9,10]],
           [[1,2,3,4],[4,5,6,7],[7,8,9,10]],
           [[5,2,3,4],[4,11,6,7],[7,8,4,10]]])
b

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]],

       [[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]],

       [[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]],

       [[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]],

       [[ 5,  2,  3,  4],
        [ 4, 11,  6,  7],
        [ 7,  8,  4, 10]]])

In [37]:
b.shape

(5, 3, 4)

In [39]:

b[4,2,3]

10

In [40]:
c=np.array([[1,2,8,6],[9,10,3,4],[5,6,2,2]])
c

array([[ 1,  2,  8,  6],
       [ 9, 10,  3,  4],
       [ 5,  6,  2,  2]])

In [43]:
z=np.arange(5)
z

array([0, 1, 2, 3, 4])

In [44]:
z=np.arange(8)
z

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
z=np.arange(1,8)
z

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
z=np.arange(1,50,5)
z

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [47]:
z=np.arange(0,50,5)
z

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [53]:
x=np.arange(1,26).reshape(5,5)
x
#first 5=rows second 5= coloumns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
c=np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10)])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
f=np.array([[[1,2],[3,4]],
           [[5,6],[7,8]],
           [[9,10],[0,0]]])
f

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [ 0,  0]]])

In [61]:
z=np.arange(50,0,5)
z

array([], dtype=int32)

In [65]:
z=np.arange(50,0,-5)
z

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [80]:
j=np.arange(16,-1,-1)
x=np.arange(0,-16,-1)
print(x)
j

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [78]:
a=np.arange(1,21)
print(a)
a**2

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [121]:
a=np.linspace(2,16,6)
a

array([ 2. ,  4.8,  7.6, 10.4, 13.2, 16. ])

In [123]:
j=0
for i in a:
    print(a[j+1]-a[j])

2.8
2.8
2.8
2.8
2.8
2.8


In [122]:
for i in range(len(a)-1):
    print(a[i+1]-a[i])

2.8
2.8
2.799999999999999
2.8000000000000007
2.8000000000000007


In [132]:
b=np.ones(8)
b

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [135]:
print('THIS IS TWO DIMENSIONAL ARRAY')
print(np.ones((3,3)))

THIS IS TWO DIMENSIONAL ARRAY
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [136]:
print('THIS IS TWO DIMENSIONAL ARRAY')
print(np.ones((3,3,4)))

THIS IS TWO DIMENSIONAL ARRAY
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [140]:
print('THIS IS TWO DIMENSIONAL ARRAY')
print(np.ones((5,3,5)))

THIS IS TWO DIMENSIONAL ARRAY
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [6]:
import numpy as np

In [5]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
c=np.zeros((3,3,3,4))
c

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [13]:
b=np.array([[8,7,5],[10,3,9],[2,8,4]])
b

array([[ 8,  7,  5],
       [10,  3,  9],
       [ 2,  8,  4]])

In [16]:
b[:,1],b[2,:]

(array([7, 3, 8]), array([2, 8, 4]))

In [22]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
#to access multiple rows in array
a[[1,3],:],a[:,[3,4]]

(array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]]))

In [30]:
a[1,:],a[:,1]

(array([ 6,  7,  8,  9, 10]), array([ 2,  7, 12, 17, 22]))

In [37]:
print(a[[1,2],[3,4]])
a[[2,3],[4,1]]

[ 9 15]


array([15, 17])

In [44]:
a=np.random.randint(0,100,9).reshape(3,3)
a

array([[38, 92, 53],
       [31, 11, 63],
       [51,  9,  6]])

In [50]:
#0= column 1= row to get the minimum and max value of the array elemnts

In [46]:
a.min(axis=0)

array([31,  9,  6])

In [47]:
a.max(axis=1)

array([92, 63, 51])

In [48]:
a.min(axis=1)

array([38, 11,  6])

In [49]:
a.max(axis=0)

array([51, 92, 63])

In [51]:
a.sum(axis=0)

array([120, 112, 122])

In [52]:
a.sum(axis=1)

array([183, 105,  66])

In [53]:
c=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [54]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [58]:
#add one by one (1+2+3+4+5........)
print(c)
np.cumsum(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120], dtype=int32)

In [65]:
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3],[2,3,4]])
print(a)
print(b)
a-b

[[1 5 3]
 [4 5 6]]
[[5 4 3]
 [2 3 4]]


array([[-4,  1,  0],
       [ 2,  2,  2]])

In [72]:
#wrong matrix multiplication
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3],[2,3,4]])
a*b

array([[ 5, 20,  9],
       [ 8, 15, 24]])

In [73]:
#wrong matrix multiplication
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3],[2,3,4]])
a*b
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [69]:
#correct matrix muliplicaion
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3],[2,3,4]]).transpose()
print(a)
print(b)
np.dot(a,b)

[[1 5 3]
 [4 5 6]]
[[5 2]
 [4 3]
 [3 4]]


array([[34, 29],
       [58, 47]])

In [77]:
#horizontal stacking of array b1 is placed in a1 side and b2 in a2
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3,7],[8,2,3,4]])
np.hstack((a,b))

array([[1, 5, 3, 5, 4, 3, 7],
       [4, 5, 6, 8, 2, 3, 4]])

In [79]:
#vertical stack
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3,7],[8,2,3,4]])
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [84]:
#vertical stack work oly for same dimension equal rows and cols
a=np.array([[1,5,3],[4,5,6]])
b=np.array([[5,4,3],[2,3,4]])
np.vstack((a,b))
#this double bracket should use o bind multiple values in a stack

array([[1, 5, 3],
       [4, 5, 6],
       [5, 4, 3],
       [2, 3, 4]])